# Content #
title: Presentation
subtitle: Just a Test

# Author #
author: Moritz R. Schulz
institute: Hochschule Schmalkalden
place: Schmalkalden
date: \today

# Document Setup #
lang: de-DE
babel-lang: ngerman

# Figures #
figureTitle: Abbildung
figPrefix:
  - Abbildung
  - Abbildungen

# Tables #
tableTitle: Tabelle
tblPrefix:
  - Tabelle
  - Tabellen
