# Content #
title: Presentation
subtitle: Just a Test
author: Moritz R. Schulz
institute: Hochschule Schmalkalden
place: Schmalkalden
date: 01.01.1970

# Language Setup #
lang: de-DE
babel-lang: ngerman

# Figures #
lofTitle: Abbildungsverzeichnis
figureTitle: Abbildung
figPrefix:
  - Abbildung
  - Abbildungen

# Tables #
lotTitle: Tabellenverzeichnis
tableTitle: Tabelle
tblPrefix:
  - Tabelle
  - Tabellen
